builds:
  - main: ./kontrolio.go
    id: "kontrolio"
    binary: kontrolio
    goos:
      - darwin
      - linux
      - windows
      - freebsd

brews:
  - name: kontrolio
    goarm: 6

    tap:
      owner: marcelovicentegc
      name: homebrew-taps
      branch: main

    commit_author:
      name: marcelovicentegc
      email: marcelovicentegc@gmail.com

    commit_msg_template: "chore({{ .ProjectName }}): bump version {{ .Tag }}"
    homepage: "https://kontrolio.com/"
    description: "Time tracking through your CLI."
    license: "MIT"

    test: |
      system "#{bin}/kontrolio --version"
